//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarMatrixData.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Company
    {
        public Company()
        {
            this.Car = new HashSet<Car>();
            this.Brands = new HashSet<Brands>();
            this.CarModel = new HashSet<CarModel>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<Car> Car { get; set; }
        public virtual ICollection<Brands> Brands { get; set; }
        public virtual ICollection<CarModel> CarModel { get; set; }
    }
}
