//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarMatrixData.Models
{
    #pragma warning disable 1573
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Common;
    using System.Data.Entity;
    using System.Data.Entity.ModelConfiguration;
    using System.Data.Entity.Infrastructure;
    
    internal partial class Record_Mapping : EntityTypeConfiguration<Record>
    {
        public Record_Mapping()
        {                        
              this.HasKey(t => t.Id);        
              this.ToTable("RecordSet");
              this.Property(t => t.Id).HasColumnName("Id");
              this.Property(t => t.Brands).HasColumnName("Brands");
              this.Property(t => t.Model).HasColumnName("Model");
              this.Property(t => t.City).HasColumnName("City");
              this.Property(t => t.Time).HasColumnName("Time");
              this.Property(t => t.Both).HasColumnName("Both");
              this.Property(t => t.Gender).HasColumnName("Gender");
              this.Property(t => t.Address).HasColumnName("Address");
              this.Property(t => t.Zip).HasColumnName("Zip");
              this.Property(t => t.Lat).HasColumnName("Lat");
              this.Property(t => t.Lnt).HasColumnName("Lnt");
         }
    }
}

