//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarMatrixData.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Record
    {
        public int Id { get; set; }
        public int BrandsId { get; set; }
        public int ModelId { get; set; }
        public string City { get; set; }
        public int BuyYearId { get; set; }
        public Nullable<System.DateTime> Both { get; set; }
        public bool Gender { get; set; }
        public string Address { get; set; }
        public string Zip { get; set; }
        public Nullable<double> Lat { get; set; }
        public Nullable<double> Lnt { get; set; }
    
        public virtual Brands Brands { get; set; }
        public virtual Models Models { get; set; }
        public virtual BuyYear BuyYear { get; set; }
    }
}
